### ISSUE TITLE
Maximum database size on 32bit architectures

### ISSUE THREAD

**Issue by mbertschler** [boltdb/bolt#280]
I am interested in using bolt on ARM devices.
https://github.com/boltdb/bolt/blob/master/bolt_arm.go as well as `bolt_386` mentions a maximum mmap size of 256MB. Is the mmap size correlated to the maximum database size, or can these architectures have databases that are larger than 256MB?
Maybe this could be clarified in the readme Limitations section?

**Comment by benbjohnson** [comment]
Bumped up to 2GB: https://github.com/boltdb/bolt/pull/281

I'll have to add a section in the docs separately.

**Comment by mbertschler** [comment]
2GB on 32 bit sounds perfect, thank you!

**Comment by davecgh** [comment]
Are there any plans to allow larger sizes on 32-bit?

I would really like to switch over to using bolt for the metadata storage for [btcd](https://github.com/btcsuite/btcd), but as you can imagine, the database size of Bitcoin can grow quite large.  This is especially true when you start to deal with optional address indices.  It will easily exceed 2GB which would make it unusable on 32-bit platforms.

**Comment by mbertschler** [comment]
I guess not, because bolt relies on memory mapped files just like MongoDB. Allowing a Database bigger than 2GB would require serious workarounds as this is the maximum size for mmaped files on 32-bit architectures. http://blog.mongodb.org/post/137788967/32-bit-limitations

The only option on your side would be to split the data into multiple databases.

**Comment by benbjohnson** [comment]
@davecgh As @mbertschler mentioned, 32-bit architectures have a limited address space so we can't physically map the data file into that space. Bolt files mmap to a contiguous block of memory and on a 64-bit address space that's not a problem because it's a ridiculously huge space. For 32-bit machines you can likely get into other issues of memory fragmentation before you reach the full available address space.

**Comment by DavidVorick** [comment]
Rather than make a new issue, I decided to bump this one.

Are there any plans to support >2GB database sizes on 32bit machines? Our users are starting to run into issues, and it's not an option for us to keep the database below 2GB anymore. Our alternative is to drop support for 32bit machines.

Thanks, and I understand if there's no plans to add support for this.

**Comment by benbjohnson** [comment]
@DavidVorick I'd love to support >2GB databases on 32-bit systems but unfortunately since Bolt is mmap'd there's limited memory address space to use. It wouldn't be feasible to support larger databases without completely rewriting the database.
