### ISSUE TITLE
use case - analysis of whether a domain, partial URL, or whole URL is in a 'set'

### ISSUE THREAD

**Issue by matzhouse** [boltdb/bolt#289]
Hi guys,

I've got a use case for Bolt i'm considering - mainly due to speed considerations. Lookups need to be super fast on globally distributed front ends, but the update schedule isn't that frequent so a possible idea would be to distribute a bolt db file to all nodes.

The idea would be to look up a whole URL and see if any part of it matches a list of either domains, partial URLs or whole URLs - the 'match' could hold some meta data as well.

I was thinking it might be good to have a bucket per domain, but apparently that might not be very efficient, the number of domains could hit the millions eventually - I enquired about this on twitter and got that response.

So as a start i'm thinking..

Step 1 - look up domain - if any domain/partial/full is in the db then we know to continue the match, otherwise we can carry on knowing it's not in there - but maybe the meta data could point to if there's any partial matches or full matches under the domain so we know which ones to look up.

- Step 2 - partial match ie. domain.com/news - this is the tricky one? I'm not sure who to minimise lookups, single record for all matches and search through the result? or is there some cleverer way?

- Step 3 - full match - simple, look up key

Any thoughts on that or any ideas that might minimise lookups? I'm not sure of the implications of the size of single records, ie is there a point they become less efficient?

Thanks for any input!

**Comment by benbjohnson** [comment]
Sorry for the long delay in getting back to you. The biggest reason against a bucket per domain is if you're going to have a lot of domains that don't have much data under them. It's OK if the data for a bucket takes up less than a page (4KB) but once it grows beyond that it'll split into two page plus a parent branch page. Then you're taking up 12KB for a little over 4KB of data.

One option you could do is to store the whole URL as the key initially and then have a separate goroutine periodically sweep for URLs which share a common domain and move them into a bucket. When you're iterating over the root bucket anything with a `nil` value returned from `Get()`, `Next()`, `Prev()`, etc will be  a bucket so you can just drill into to there to find the paths.

As for the size of individual records, values don't cause any inefficiencies. Large keys be less efficient since some of the keys get duplicated in the branch nodes in a b+tree. I'd try to keep the average key size relatively small.

You also may want to look at bloom filters if you think you'll have a lot of lookups for URLs that don't exist.

I hope this helps! Let me know if you have any other questions.
