### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by j** [boltdb/bolt#293]
I have a few questions before diving completely head first into Bolt.

* How many buckets can bolt handle, and does performance degrade with the use of many buckets?
* What's the use-case of nesting buckets

And, Dealing with relationships, which scenario would be best?

A Test has many Variations.

1. I have a "Tests" bucket, and I nest a bucket called "Variations" in it prefixed like, "T:{test id}:V", and that bucket contains it's Variations.  I can then iterate over that bucket completely for the test's variations.
2. I have a "Tests" bucket, a "Variations" bucket, and a "TestsVariations" bucket. "TestVariations" has keys prefixed with the variation ID, I find those and each match is a variation. (I suppose I can also just have the key prefixed with the Test id and have the variations as the value and get all those keys from the Variations bucket.... but if this gets large, I assume it may be a problem.

Am I way off?

**Comment by benbjohnson** [comment]
> How many buckets can bolt handle, and does performance degrade with the use of many buckets?

There's not a limit on buckets. They can be inefficient with regards to space if you store a small amount of data in each one. If the size of the data in a bucket barely exceeds a 4KB page then it'll split into two leaf pages and one parent branch page. So if you have a bucket with 5KB of data it still needs three 4KB pages store it in for a total of 12KB. Space tends to even out more when you have larger data sets in a bucket.

> What's the use-case of nesting buckets?

The original use case was for a database that stored web site page views grouped by session. The top level bucket stored sessions and each session was a bucket that stored all the page views. It suffered from some of the poor utilization issues mentioned above but it went *really* fast since the data was sorted exactly how I needed to read it (e.g. by session, then by timestamp).

Another use case is if you need to segment data and you don't want your code to accidentally grab data from the wrong segment. I've used buckets in multi-tenant systems to keep one user's data completely separate from another user's data without having to make a Bolt DB for each user.

> And, Dealing with relationships, which scenario would be best?

When I model relationships in Bolt I look at the cardinality of the data and how the data is accessed. There's essentially 3 models I consider:

1. *Small cardinality, never accessed directly* - This would be a situation like if a `User` could have multiple names. I would just make a `users` bucket and encode the names directly into the user object that I encode.

2. *Small cardinality, accessed directly* - This is a situation like the `Test` & `Variation` example you gave. A "test" probably doesn't have thousands of variations but the variations are probably accessed directly by a `VariationID`. I would make a `tests` bucket and a `variations` bucket and simple store the list of variation ids into the test object. I'd probably also store the parent test id into the variation object as well so you can go back and forth between the two objects. If you're using something like `gogoprotobuf` then it's really fast to decode a `Test` struct to grab your `Test.VariationIDs` list and then traverse into the "variations" bucket.

3. *Large cardinality* - This is a situation where a parent object has thousands or tens of thousands of child objects. In this case a subbucket is probably appropriate. It gives you a nice isolated space to put the child objects. Another option is to create a single bucket to act as an index and you simply make the key `<parentID><childID>` and don't set a value. That'll let you iterate over a range of `childIDs` for a given `parentID`.

One more thing to note. I typically use integer IDs when possible because they're easy to work with, fixed size and Bolt can generate them for you per bucket. I generate them using the `Bucket.NextSequence()` call and store them using `binary.BigEndian.PutUint64()` since big-endian numbers are byte-sortable.

I hope this all helps. Let me know if you have any questions.

**Comment by j** [comment]
Thanks @benbjohnson!  Yep, I pretty much nailed it on the head, so that's good.  Will hopefully get this project put into production and give it a few million requests / day on various instance sizes to check out performance and see how it scales.

Great project!

**Comment by joyrexus** [comment]
@benbjohnson This is valuable info!  Would you consider adding it the README under **Best Practices** or **FAQ**?  Or better yet, enable the repo's wiki and use it for this kind of supplementary documentation?
