### ISSUE TITLE
Opening database read only

### ISSUE THREAD

**Issue by ktmn** [boltdb/bolt#302]
How come when I open the database like this

    bolt.Open("my.db", 0444, nil)

I can still put things in buckets? I expected to get some sort of error, that the database is read only. Am I misunderstanding the reason for passing this variable to the Open() or is it simply not working cause I'm on a Windows with full admin rights and I "have the permissions anyway"?

**Comment by kemist** [comment]
I think your last statement is probably correct, your account is an Administrator so it has the right to do what it pleases. Similar to running as root on *nix. If your inspect the file properties is it marked as read only? What happens if you run `bolt.Open("my.db", 0444, nil)` as a non-admin?

Bolt will do what the file system permits it to do.

**Comment by benbjohnson** [comment]
I agree that it is strange. Bolt does a call to `os.OpenFile(db.path, os.RDWR | os.CREATE, mode)` when you open it. Doing an `os.CREATE` and a read-only mode will let you create a file that is only writeable by that process. If you close and reopen it then you get a permissions error. That's a byproduct of how Unix works. I assume it's something similar on WIndows.

I can't think of a good way to fix it without changing Bolt's API. I like that Bolt will create a database if it doesn't exist so I think this is just a trade off of having that feature.
