### ISSUE TITLE
List and test for keys without retrieving values

### ISSUE THREAD

**Issue by kalafut** [boltdb/bolt#321]
I'm using Bolt as part of a content-addressable storage system. The keys are determined by hashing the data. A number of operations depend only on the keys, and automatically having associated values pulled is an unnecessary operation, and possibly expensive for large values.  For example:

- Before storing an item, I want to be able to check whether a given key is already present, since there's no need to rewrite the data.
- I'd like to iterate over keys without receiving the values.

I think the existing Cursor pattern could address these cleanly, since I can use Seek as an "exists()" function. Maybe Cursor could have an internal flag to not return values, and KeyCursor() could make this variant?  Or Cursor takes an optional parameter?  The Cursor function interfaces would remain the same, but would simply return nil for the values (and not get them, of course).

Thanks. Really enjoying Bolt!

**Comment by benbjohnson** [comment]
Bolt is a zero copy database so when you iterate over key/values or seeking to a specific key the `[]byte` return values are just pointers to the underlying mmap. Since the key & value will be on the same page, there's no overhead to returning the value when you're looking up the key. That's also why it's not safe to use the `[]byte` return values outside of the transaction -- those pages can get reclaimed by Bolt and you'll be pointing at invalid data.

**Comment by benbjohnson** [comment]
Let me know if that makes sense or if you have any other questions!

**Comment by kalafut** [comment]
That makes sense, and does keep things simple. A suggestion might be to add a similar explanation to the README, for the next person fretting over the lack of Exists() or HasKey().

**Comment by phrozen** [comment]
I'm also looking for this kind of functionality. Retreiving the ```value``` on a ```key``` for existance check might incur in unecessary disk io operations and disk read for a large ```value``` (ie. 20-50MB). Of course one can iterate (seek) the whole bucket but that seems like an inefficient O(n) lookup, while doing something exactly like ```bucket.Get()``` uses a more efficient tree search. 

From what I can gather, when you say the return values are just pointers to the underlying ```mmap``` means that the reading operation has no overhead, but it is still being done, and incurs in resources when not needed (more so with larger values). Something like ```func (b *Bucket) Exist(key []byte) bool ``` is what I think he means, that would use the internal search of bolt for existance and would never read the data (values).

**Comment by benbjohnson** [comment]
@phrozen Bolt only returns the pointers to the key and value and those live next to each other in a single page. Because they're pointers to the underlying mmap, the entire value is not paged into memory unless it is actually used.

For example, calling `Bucket.Get()` that returns a 50MB value will return your key and value byte slices but only the first ~4KB of the value will be read from disk and paged into memory because that's what fits on a page. It has the same overhead as calling `Get()` on a zero length value. 

From a perfomance standpoint, the returning of an extra pointer is almost non-existent. Reading the page from main memory (~100ns) will have far more overhead than the additional ops required for an additional return parameter (~1-2ns).

**Comment by phrozen** [comment]
@benbjohnson Thanks for the clarification, so the actual read of the ```value``` is not done until you call  ```copy()``` on the ```value``` right? I think this should be documented, checking for existence should be as easy as ```bucket.Get()``` and checking for ```nil```.

**Comment by benbjohnson** [comment]
@phrozen Not quite. The 4KB page that the value starts on is read into memory. If your value is larger than 4KB then those pages will only be read as they're accessed. That's handled entirely by the OS's page cache.
