### ISSUE TITLE
The bolt cmd is poorly designed and out of date

### ISSUE THREAD

**Issue by anacrolix** [boltdb/bolt#325]
The bolt cmd binary uses old-style functions like println. It doesn't support nested buckets. It's missing a put command. It doesn't handle command line arguments properly. The list goes on. I think it needs a rewrite.

**Comment by benbjohnson** [comment]
I've been wanted to rewrite `cmd/bolt` for a while but I mainly haven't had the time. I mainly want to get rid of the `cli` dependency. That library is a fine tool but I just want to avoid dependencies in Bolt.

The `bolt` tool is mainly meant to be a simple debugging tool. It's hard to make a good generalized data access tool since users can store their keys and values in any format. I'm less concerned about trying to support `put` since writes should be implemented by the application using Bolt.

What do you mean that CLI arguments aren't handled properly?

**Comment by kemist** [comment]
@anacrolix it's helpful if you provide examples that cover your questions/concerns. I can help create some repro cases for you if you want to describe them in english as opposed to code.

**Comment by benbjohnson** [comment]
CLI rewritten in https://github.com/boltdb/bolt/pull/352.
