### ISSUE TITLE
random writes performance decreases significantly as the number of keys in the database increase

### ISSUE THREAD

**Issue by xiang90** [boltdb/bolt#355]
I use the same batch-size but different total number of keys to run the benchmark. 
I notice 
```
Bulk loading a lot of random writes into a new bucket can be slow as the page will not split until the transaction is committed. 

Randomly inserting more than 100,000 key/value pairs into a single new bucket in a single transaction is not advised.
```
So I set the batch-size to 1000, which is fairly reasonable. 

I still found some unexpected results here. 

```
./bolt bench --write-mode 'rnd' --count 10000 --batch-size 1000
# Write	69.37272ms	(6.937µs/op)	(144154 op/sec)

./bolt bench --write-mode 'rnd' --count 100000 --batch-size 1000
# Write	2.458685203s	(24.586µs/op)	(40673 op/sec)

./bolt bench --write-mode 'rnd' --count 1000000 --batch-size 1000
# Write	49.201247217s	(49.201µs/op)	(20324 op/sec)

 ./bolt bench --write-mode 'rnd' --count 5000000 --batch-size 1000
# Write	5m55.748260476s	(71.149µs/op)	(14055 op/sec)
```

I understand that as the number of keys grows the height of B+tree increase, so bolt might have more fsync per write. But I do not expect about 10x decrease from 6us to 71us.

Is this normal?

**Comment by xiang90** [comment]
But interestingly, if I set --batch-size to 1, the performance decrease is very reasonable.
```
./bolt bench --write-mode 'rnd' --count 10000 --batch-size 1
# Write	4.842807128s	(484.28µs/op)	(2064 op/sec)

./bolt bench --write-mode 'rnd' --count 100000 --batch-size 1
# Write	51.966061662s	(519.66µs/op)	(1924 op/sec)

./bolt bench --write-mode 'rnd' --count 1000000 --batch-size 1
# Write	9m21.77276479s	(561.772µs/op)	(1780 op/sec)
```

After doing this, I realized that previous significant decrease might be caused by inefficient batching? The more keys bolt have the less chance that the batched changes falls into the same os page? Bolt is not able to batch multiple page sync into one syscall?

**Comment by xiang90** [comment]
@benbjohnson 

I got the svg for profiling at https://github.com/xiang90/boltp.

**Comment by benbjohnson** [comment]
Hmm, the SVG between the 100k and 5M are almost identical. It doesn't look like there's something weird going on.

I think the issue is that random writes in batches of 1K across a 10K key dataset are going to cause multiple writes to occur per page whereas 1K writes across a 5M key dataset will only have 1 write per page.

With the default `bolt bench` parameters, you have 8 byte keys and 32 byte values. That's 40b plus a 16b header written into a page with a fill percent of 0.5. That's 36 records per page. A 1K batch is 10%  of your dataset for 10K and 0.02% of your 5M dataset. Actually, your average dataset for your 10K version is actually 5K since you're adding 1K over 10 batches so your 1K batch is 20% of your dataset on average.

I think it's just getting the benefit of batching multiple writes into each page.
