### ISSUE TITLE
[support request/code review] Efficient use of Bolt

### ISSUE THREAD

**Issue by xyproto** [boltdb/bolt#380]
Hi,

I'm using Bolt in [simplebolt](https://github.com/xyproto/simplebolt/blob/master/simplebolt.go). However, being new to Bolt, I am not fully confident that Bolt is being used efficiently. If someone could just look over the code and check if the use is reasonably efficient, that would be great.

Best regards,
   Alexander Rødseth

**Comment by benbjohnson** [comment]
Overall the usage looks good. Two suggestions (after taking a quick glance):

- Be sure to check errors from `View()` and `Update()`. For example, there's a missing error check in `NewList()`.

- It's more efficient to use `binary.BigEndian.PutUint64()` instead of `fmt.Sprintf()` to represent ids. For one thing, it's much faster to encode & decode. Second of all, when you use a stringified representation then it won't insert sequentially. For example, the numbers `1,2,10` get sorted as `1,10,2` when you use `fmt.Sprintf()`.

I hope that helps!

**Comment by xyproto** [comment]
Thank you! I really appreciate it. Additional error handling is now in place and I'll be looking into your suggestion to use `binary.BigEndian.PutUint64()` instead.
