### ISSUE TITLE
put doesn't return error when putting nil

### ISSUE THREAD

**Issue by yichengq** [boltdb/bolt#412]
```
func TestBolt(t *testing.T) {
	db, err := bolt.Open("test", 0600, nil)
	if err != nil {
		log.Fatalf("backend: cannot open database at test (%v)", err)
	}
	tx, err := db.Begin(true)
	if err != nil {
		log.Fatal(err)
	}
	b, err := tx.CreateBucket([]byte("test"))
	if err != nil {
		log.Fatal(err)
	}
	err = b.Put([]byte("foo"), nil)
	if err != nil {
		log.Fatal(err)
	}
	v := b.Get([]byte("foo"))
	if v == nil {
		t.Errorf("failed to get the put key")
	} else {
		t.Logf("val = %s", v)
	}
	tx.Commit()
	db.Close()
	os.Remove("test")
}
```

I would expect it to return error based on its comment `Returns an error if the bucket was created from a read-only transaction, if the key is blank, if the key is too large, or if the value is too large.`

**Comment by benbjohnson** [comment]
IIRC, nil is converted to an empty slice in Put(). Returning nil is reserved for non-existent keys whereas putting nil creates a blank key. It probably shouldn't allow a nil value but I don't want to change it because of backwards compatibility.

**Comment by chrsm** [comment]
`cloneBytes` returns an empty slice when a nil value is passed to it - so Put is fine.

Based on the comment, specifically, it's not breaking expected behavior - it says nothing about the minimum size of a value. For what it's worth, the caller should be responsible for ensuring it's writing actual data. For all boltdb knows, I could just want to reserve a key - especially if passing nil is functionally equivalent to passing an empty slice.

**Comment by benbjohnson** [comment]
Well said. :)
