### ISSUE TITLE
Hotswap and multiple databases

### ISSUE THREAD

**Issue by phrozen** [boltdb/bolt#425]
By reading the code I can see the locks and mutex exist internally to close the database for example, but I don't see them exposed anywhere, use case would be Hotswap of an entire database.

On the other hand, how advisable is to run a program with multiple databases (maybe opened at runtime on demand, or to separate logic from storage for archiving purposes). How much does it cost the DB object?  (index, io, memory, etc...) In order to determine if it is feasible to either open a database when needed (on demand) or open them at startup and just having the object there ready when needed.

**Comment by benbjohnson** [comment]
The internal locks aren't exposed because it seems like an easy way to shoot yourself in the foot. If you don't get the lock ordering right then you can easily deadlock your database.

A hotswap feature would be nice. `Tx` currently implements `io.WriterTo`. It'd be nice if `DB` implemented `io.ReaderFrom`.

As for multiple databases, it shouldn't be a problem to run a bunch and it shouldn't take long to open. `DB.Open()` is essentially a 8KB file handle read and then an `mmap()` call. There's hardly any overhead at the DB level. Most of your overhead exists with the free page list but that doesn't change whether you have one `DB` or a bunch.
