### ISSUE TITLE
Deleting items from a bucket during ForEach

### ISSUE THREAD

**Issue by DavidVorick** [boltdb/bolt#426]
If you delete items from a bucket during a ForEach, you can get non-deterministic behavior (the specific problem I ran into was that sometimes not all items would be reached).

Given that go maps work the same way, I probably should have expected this, but it's not documented that you aren't supposed to delete elements from a bucket while iterating through it with ForEach.

**Comment by davecgh** [comment]
While I agree it should probably be called out on `ForEach` as I ran into it once upon a time too, the behavior is in fact documented under [Cursor](https://godoc.org/github.com/boltdb/bolt#Cursor).

"Changing data while traversing with a cursor may cause it to be invalidated and return unexpected keys and/or values. You must reposition your cursor after mutating data."

Ergo the same applies to `ForEach` since it uses a cursor under the hood.

**Comment by benbjohnson** [comment]
@DavidVorick Can you submit a documentation PR?
