### ISSUE TITLE
Horizontal scaling tools  - ideas

### ISSUE THREAD

**Issue by joeblew99** [boltdb/bolt#485]
There are a few tit bits of info around about this.
It would maybe useful to have them as a contributed ?
1. Webadmin UI.
- similar to the rethinkdb one

2. Sharding
- raft based consensus
- sounds a bit like what consul and cockroach do.
- other aspects

I hope this raises discussions here about this

**Comment by xiang90** [comment]
I believe this is out of the scope of boltdb.

**Comment by benbjohnson** [comment]
Yes, those are definitely good ways to scale bolt (I've done number 1 and 2) but I agree that it's out of scope of this project. Bolt is meant to be a pretty low level primitive to build on top of.

**Comment by chrsm** [comment]
@benbjohnson Any chance you'd be willing to describe a bit of what you implemented for (1) and (2)?

**Comment by joeblew99** [comment]
@benbjohnson me too !

i would like to look at it, and see if i can take it further

**Comment by benbjohnson** [comment]
@chrsm Here's a high level of the approaches taken for both:

1. Sharding - Bolt was used as the backing store for an analytics server. All the events for the company (e.g. web site views, account creation, orders, etc) all ran through a Kafka server. We were able to partition Kafka topics by account and then the Bolt servers would read in those streams of events and build analytics based on that. We had 64 partitions that were allocated to N nodes based on a consistent hashing scheme. That meant that we could add nodes to the cluster and rebalance as needed. Nodes also had a replication factor of 3 so the same partition existed on 3 nodes. In this case Kafka simply acts as a distributed write ahead log.

2. Raft-based consensus - We used Raft to append commands that would get executed on all nodes in  the cluster. Those commands would alter the Bolt database in some deterministic way so that all nodes had the same data after the commands were executed.

**Comment by chrsm** [comment]
@benbjohnson Fantastic, thanks. I apologize for hijacking this issue, as I know that it's not _strictly_ related to what BoltDB itself does - but I sincerely appreciate the knowledge dump. :)

**Comment by xiang90** [comment]
> Raft-based consensus

etcd v3 also uses raft and bolt in this way.

**Comment by benbjohnson** [comment]
@chrsm No problem. Glad to share the knowledge! :)
