### ISSUE TITLE
Provide DB truncation command for automated testing support

### ISSUE THREAD

**Issue by jacek99** [boltdb/bolt#490]
Right now when running Cucumber BDD tests against my app, I need to truncate the DB between every test to reset it back to an empty state.

There seems to be no way to easily do this without iterating through all the buckets, deleting all the keys, etc.

It would be great if there was a command that just reset the DB back to a clean empty state (but preserving all the bucket definitions of course)

**Comment by benbjohnson** [comment]
I don't see a way to do this easily for all use cases since people use buckets and keys in different way. I can see two different options that you could implement:

1. Remove the file, open a new bolt DB and reinitialize the buckets. Reinitialization shouldn't take very long assuming you don't have a ridiculous number of buckets.

2. Make a copy of the database after it has been initialized and then copy it in at the beginning of each test.

When I do automated tests I usually create a bolt database at a random temporary path and reinitialize it each time. It makes it so that tests can be run in parallel and speeds up the test suite significantly.

**Comment by jacek99** [comment]
Thanks, went with that approach. Seems very fast to regenerate bucket defs on an new file so not an issue.
