### ISSUE TITLE
performance: large concurrent inserts annihilated by memmove

### ISSUE THREAD

**Issue by dustinhiatt-wf** [boltdb/bolt#509]
I have the need to insert 2 million keys as quickly as possible.  My keys are randomly distributed and I use a simple partitioning algorithm to divide my writes amongst 64 partitions.  I noticed, especially moving from one million inserts to two million, a massive performance bottleneck in memmove.

```
Showing top 10 nodes out of 60 (cum >= 0.01mins)
      flat  flat%   sum%        cum   cum%
  1.51mins 67.74% 67.74%   1.51mins 67.74%  runtime.memmove
  0.34mins 15.05% 82.80%   0.34mins 15.05%  MCentral_Grow
  0.08mins  3.41% 86.21%   0.08mins  3.41%  scanblock
  0.06mins  2.88% 89.09%   0.06mins  2.88%  runtime.usleep
  0.03mins  1.25% 90.33%   0.03mins  1.25%  syscall.Syscall
  0.03mins  1.14% 91.47%   0.03mins  1.14%  runtime.MSpan_Init
  0.02mins  0.99% 92.46%   0.02mins  0.99%  runtime.cmpbody
  0.02mins  0.85% 93.31%   0.03mins  1.17%  runtime.mallocgc
  0.01mins  0.59% 93.90%   0.04mins  1.75%  runtime.makeslice
  0.01mins  0.57% 94.47%   0.01mins  0.57%  runtime.mach_semaphore_signal
```

Looking at the origin, I discovered that it was in the key insertion for nodes.  The copy function there is going to copy all those structs.  I changed inodes to be a list of pointers instead:

```
Showing top 10 nodes out of 79 (cum >= 610ms)
      flat  flat%   sum%        cum   cum%
   14690ms 41.32% 41.32%    14690ms 41.32%  MCentral_Grow
    4700ms 13.22% 54.54%     4700ms 13.22%  scanblock
    2290ms  6.44% 60.98%     2290ms  6.44%  runtime.memmove
    1820ms  5.12% 66.10%     1820ms  5.12%  runtime.usleep
    1690ms  4.75% 70.86%     1690ms  4.75%  syscall.Syscall
    1290ms  3.63% 74.49%     1680ms  4.73%  runtime.mallocgc
    1060ms  2.98% 77.47%     1060ms  2.98%  runtime.MSpan_Sweep
    1010ms  2.84% 80.31%     2850ms  8.02%  runtime.makeslice
     990ms  2.78% 83.09%      990ms  2.78%  runtime.writebarrierptr
     610ms  1.72% 84.81%      610ms  1.72%  runtime.MSpan_Init
```

I'm assuming this is left as a list of structs to keep sets/gets on small datasets more performant, is that the case?

**Comment by benbjohnson** [comment]
@dustinhiatt-wf The `[]inode` is used to minimize additional objects needing to be collected. Once you change it to `[]*inode` then you need to allocate the slice as well as every single individual inode. It may speed this particular case up but it's going to create a lot of GC pressure that will cause most other applications to slow down.

The issue in this case is that Bolt won't split nodes until it commits so if you're randomly inserting into a single node (which would happen if you're inserting all keys into a new bucket) then that single node will get large and `memmove()` becomes an issue.

There's two solutions:

1. Batch your writes into 10,000 - 20,000 inserts at a time. This will create nodes so that you're not getting one gigantic node you're inserting into.

2. Sort all your keys before inserting. Sequential appends to a bucket are _significantly_ faster than random writes. You can get up to 400K keys/sec if you're doing appends which means you should be able insert your 2M keys in a few seconds after they're sorted.

**Comment by dustinhiatt-wf** [comment]
@benbjohnson Sounds good, I'll give it a try.
