### ISSUE TITLE
Add Option to Encrypt the Database File

### ISSUE THREAD

**Issue by icub3d** [boltdb/bolt#529]
I would like to see an option to encrypt the database file. I would be happy to do the work and submit a pull request but before I do it, it would probably be a good idea to come to a conclusion on how it should work.

My thinking would be to allow a new option that allows for a wrapper to be provided. This should be a generic wrapper so encryption need not be the only reason to have it. 

The write part seems to be fairly easy. It looks like all writes in boltdb use the db.ops struct which means we could simply adjust that during the Open call to wrap that call with the wrapper option if there is one.

The read part is a bit more difficult. It looks like there are several functions that pull pages from byte slices where the underlying data comes from mmaps. I'm guessing in these cases we'd need to read the buffer, copy it, decrypt the copy, and return that.

How feasible is this? Is it worth the cost? What parts am I missing?

**Comment by benbjohnson** [comment]
@icub3d Encryption seems like a concern that's outside the scope of Bolt. There's a lot of factors to take into consideration (e.g. what kind of encryption, do you only encrypt values or keys too or on the whole DB?).

Since Bolt operates at a low-level it seems like you could build this on a layer above Bolt. You could also create Bolt on an encrypted file system and avoid the issue of encryption at the application layer entirely.

**Comment by xiang90** [comment]
@benbjohnson The only downside of doing this outside bolt is that the page structure and key structure might leak out. But this does not seem like a huge issue.

**Comment by icub3d** [comment]
@benbjohnson, I'm fine if the consensus is that it's out of scope. I'll just roll my own. Most of the considerations you mention can be left to the user with the wrapper model. Their wrapping functions would implement encryption or anything else they might want to do with the file/pages. Bolt would simply just provider an option to wrap read/writes to the metadata and pages with a provided function.

Building it on top of bolt means that some information is leaked about the database, which isn't what the project I'm currently working on would like. The need I'm looking to solve requires  that a key/value store be able to be passed around securely to various systems. They may have encrypted file systems but they may not. Only systems with knowledge of the key should be able to get any information from the key/value store.

If I encrypt the key/value pairs but not the entire database, information like the number of keys, rough size of keys, and more can be leaked. One could even open the database and iterate over buckets and keys to gain information about the structure and hierarchy of the system. Encrypting the entire database, including the meta and page data means that without the key, the database file, if properly encrypted, is no different than random data.

**Comment by benbjohnson** [comment]
@icub3d If the implementation is as simple as wrapper functions to read/write to pages then I'd be open to including it in the main repo. If it involves a more significant rework of the code then I would rather see it as a fork.

One issue I can see is that Bolt works on fixed block sizes and splits items into pages based on that size. It seems like you wouldn't know the encrypted size of data at the time of splitting. Maybe that could be resolved without being too invasive to the codebase. I'm not sure.

**Comment by benbjohnson** [comment]
Closing since this hasn't been active. @icub3d ket me know if you want to reopen this and discuss it further.

**Comment by thinkhy** [comment]
I encounter this problem when I prepare a package that invokes Boltdb's functions and will be delivered to some customers. Customers place heavy emphasis on data security, so my boss is wondering if db file of Boltdb can be encrypted, but the answer is NO by now ...

**Comment by kron4eg** [comment]
@thinkhy encrypted FS could solve this problem

**Comment by benbjohnson** [comment]
@thinkhy I've had several requests for being able to use bolt purely in-memory which I think I might implement. It would work well for encrypting small databases since you could decrypt the entire file and operate on it in-memory. It wouldn't give away any information about keys or value sizes since the whole data file is encrypted.

Of course, this wouldn't work well for large databases since you'd have to encrypt and save the entire data file on each commit (or periodically snapshot but then you lose durability guarantees).

**Comment by thinkhy** [comment]
@benbjohnson Thanks for your quick reply. For my case, we have been developing a traditional software product that would be deployed in customer's box. As a software vendor, we can not force customer to encrypt their FS, we just need to keep the product that we own secure enough.  

As you mentioned, there are two ways we can adopt: use bolt pure in memory or encrypt the whole data file, I think both ways would work for us because we just use BoltDB to buffer intermediate data and the size of data(<100MB) is not large. But now I'm not familiar with BoltDB codebase and we are approaching to release  the first demo. If possible, could you pls instruct us more about the solutions? 

Thanks again

**Comment by dimitarvp** [comment]
@benbjohnson I second @icub3d's request and I feel your suggestion of adding a simple layer above reading/writing pages seems like the path of the least resistance.

I am about to embark in a Go project that will absolutely require hiding as much of the DB as possible and as the OP suggested, using other approaches would still leak quite a lot of metadata, which is undesirable.

Would you be so kind to share if you did get to a point when you evaluated the time and effort cost of your own suggestion, please?

**Comment by joeblew99** [comment]
What about this ?

https://github.com/rfjakob/gocryptfs

Allot of the crypto is done, but it's dependent on go-fuse at the moment.

A driver interface could be added to use boltdb, instead of go-fuse. It's not going to be the same interface signature that's for sure, but you can see the idea.

**Comment by utdrmac** [comment]
This is over a year old. Is there any progress/news on encrypting boltdb?
