### ISSUE TITLE
Size overhead

### ISSUE THREAD

**Issue by jrots** [boltdb/bolt#564]
Hi, I'm test writing 1M docs, 42 bytes for value and 4 bytes for key. 
(I'm new to go so code i've written could contain some weirdness)
If I first run the program, the DB file would take up 146083840 bytes
on second run it would increase to 275611648 bytes, afterwards it would stay around 275611648 bytes. 
Where is this double increase coming from? Also there seems like a lot of overhead: 
(4 bytes + 42 bytes ) * 1M.. would expect the file size to be more around 46000000 bytes.. 
```
package main

import (
	"bytes"
	"encoding/binary"
	//	"encoding/gob"
	"fmt"
	"github.com/boltdb/bolt"
	//	"hash/fnv"
	"log"
)

type Person struct {
	Active             uint8
	HasAvatar          uint8
	Country            uint8
	Gender             uint8
	BirthDate          int32
	FilterMale         uint8
	FilterFemale       uint8
	HasQa              uint8
	IsHot              uint8
	FilterMinAge       uint8
	FilterMaxAge       uint8
	Language           uint8
	Score              uint8
	RelationshipStatus uint8
	SexualOrientation  uint8
	Latitude           float32
	Longitude          float32
	LastLoginDate      uint32
	LastMessageDate    uint32
	RegistrationDate   uint32
	LastUpdate         uint32
}

var world = []byte("world")

func main() {
	db, err := bolt.Open("bolt.db", 0644, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	//	key := []byte("hello")
	//	value := []byte("Hello World!")

	var nperson Person
	nperson = Person{1, 1, 2, 1, 10094, 0, 0, 0, 0, 18, 24, 3, 100, 1, 0, 19.1, 35.3, 20140101, 20561243, 19840914, 4995511}
	buf := new(bytes.Buffer)
	if err := binary.Write(buf, binary.BigEndian, &nperson); err != nil {
		fmt.Println(err)
	}
	fmt.Println(buf.Len())
	// store some data 1M docs
	err = db.Update(func(tx *bolt.Tx) error {
		bucket, err := tx.CreateBucketIfNotExists(world)
		if err != nil {
			return err
		}
		for i := 0; i < 1000000; i++ {
			bs := make([]byte, 4)
			binary.BigEndian.PutUint32(bs, uint32(i))
			err = bucket.Put(bs, buf.Bytes())
			if err != nil {
				fmt.Println(err)
				return err
			}
		}
		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

	// retrieve the data => read key 1000
	err = db.View(func(tx *bolt.Tx) error {
		bucket := tx.Bucket(world)
		if bucket == nil {
			return fmt.Errorf("Bucket %q not found!", world)
		}

		bs := make([]byte, 4)
		binary.BigEndian.PutUint32(bs, uint32(1000))

		err := binary.Read(bytes.NewBuffer(bucket.Get(bs)), binary.BigEndian, &nperson)
		if err != nil {
			fmt.Println(err)
		}

		fmt.Println(nperson)

		return nil
	})

	if err != nil {
		log.Fatal(err)
	}
}

```

**Comment by benbjohnson** [comment]
@jrots The reason you're seeing the database size double on the second run is that Bolt uses copy-on-write to maintain safety in the event of a crash and to provide a snapshot to read transactions that may be running (although you don't have any concurrent read txns in this example).

So when you insert a large number of large values in a single transaction then the old space can not be freed until the new values are fully written and committed. That space gets reused on the next transaction which is why you don't see the space go up in the third run.

Bolt uses extra space for several reasons. Pages split in half when they're over the page size (4KB) so that will generally double the size of your data for small values. This allows future random writes to perform faster since they will not have to split as often. Also, Bolt tends to work much better on smaller values (e.g. 32KB or less) because large values will tend to cause fragmentation since they require contiguous pages.

Finally, Bolt will automatically bump up the size of the database larger than it needs so it doesn't have to call `ftruncate(1)` on every resize.
