### ISSUE TITLE
[Question] Use of buckets for performance

### ISSUE THREAD

**Issue by gnewton** [boltdb/bolt#583]
I have a use case for a large-ish read-only boltdb database.

Does it make any difference if I (effectively) shard the database into equally sized buckets (say 32) and first do a lookup of the first 2 letters of the keys in the buckets, then retrieve the actual key in the found bucket, or is it fine putting everything in a single bucket. Would this impact performance?

Info: 
~30m items
keysize: 12bytes
value size: 2-4kb

Thanks

**Comment by benbjohnson** [comment]
@gnewton I believe it shouldn't make a difference since they're still in the same database. Sharding the database into multiple databases would probably improve performance though.

It's difficult to accurately assess the performance since it can change depending on your data, your access patterns, your hardware, etc. It's a relatively easy benchmark to put together. I'd suggest testing both approaches.

**Comment by gnewton** [comment]
Thanks for the reply. I will look into comparing over the next few weeks.
