### ISSUE TITLE
Enable tx.ForEach to iterate child buckets as well

### ISSUE THREAD

**Issue by mdlayher** [boltdb/bolt#603]
Prompted by a discussion here: https://github.com/mdlayher/prombolt/pull/1/files#r81872274.

It would appear that `tx.ForEach` does not iterate child buckets.  It would be nice if it were able to do so.

Let's say we have a bucket hierarchy as follows:

```
bolt.db
├── foo
└── bar
    └── baz
```

The following example:

```go
tx.ForEach(func(name []byte, b *Bucket) error) {
    fmt.Println(string(name))
})
```

Produces output like:

```
foo
bar
```

What I would like is for the output to be something like:

```
foo
bar
bar/baz
```

Maybe it makes sense to add a new method on `*bolt.Bucket` for doing this, such as:

```go
func (b *Bucket) ForEachChild(fn func(name []byte, b *Bucket) error) {
    // ...
}
```

**Comment by benbjohnson** [comment]
I've been thinking about adding a function to expose the `Root()` bucket on `Tx` and that would make it easy to do recursive iteration. I'm on the fence about adding a function to do recursive iteration since 1) it's pretty easy to implement by a user, and 2) it limits how the iteration is performed. For example, if a user wants to stop iterating after X number of buckets then they'd have to return a error to stop which is kinda lame. :)

**Comment by mdlayher** [comment]
I'll happily accept any solution that enables finding child buckets without checking each and every key to see if it's a bucket, using: https://godoc.org/github.com/boltdb/bolt#Bucket.Bucket.

**Comment by benbjohnson** [comment]
There's not any meta data stored about which keys contain values and which contain buckets. Unfortunately crawling all the keys is the only way to find child buckets. :-/

**Comment by mdlayher** [comment]
Gotcha.  Would it break things or have large performance or storage implications if metadata about child buckets were added?

If so, no worries.  It's just a "nice to have" but this isn't immediately necessary for me.

**Comment by benbjohnson** [comment]
Yeah, that would be a breaking change as the file format would have to be altered. Maybe for Bolt 2.0. :)
