### ISSUE TITLE
Database size doubles after reload

### ISSUE THREAD

**Issue by budkin** [boltdb/bolt#630]
The database size goes form 4194304 to 8388608, after I delete the main bucket with my data and add it again with the same data. Why is that?

**Comment by benbjohnson** [comment]
A bolt database cannot shrink. Instead it adds unused pages to a freelist. Bolt is also a copy-on-write database so when you deleted your bucket, the parent branch pages that pointed to the bucket had to be rewritten to new pages.

Bolt adds additional space in chunks so that's why there was a large jump from 4MB to 8MB. It's not using all that space for your data. Most of that space is marked as free within Bolt.
