### ISSUE TITLE
[question] how tx.WriteTo do a consistent snapshot

### ISSUE THREAD

**Issue by shuoli84** [boltdb/bolt#639]
Sorry if this is a dumb ques. 

> Bolt is a single file so it's easy to backup. You can use the Tx.WriteTo() function to write a consistent view of the database to a writer. If you call this from a read-only transaction, it will perform a hot backup and not block your other database reads and writes.

From the code, it just opens the file and do a read. But some write transactions are still modifying the file. Since we has a read tx, and make it meta0 in new file, it will hold the snapshot of the transaction. But new write txs are still writing, so we still copy new data but they just not reachable, am i right? 

And since the fill rate is around 0.5, which means the WriteTo's efficiancy is 50% maximum?

**Comment by benbjohnson** [comment]
> _Since we has a read tx, and make it meta0 in new file, it will hold the snapshot of the transaction. But new write txs are still writing, so we still copy new data but they just not reachable, am i right?_

Yes, that's correct. The meta page points to the root of the B+tree which is immutable so those pages cannot be altered while the read transaction is open. Other free pages can be overwritten but those will be ignored since they are not accessible from the root.

> _And since the fill rate is around 0.5, which means the WriteTo's efficiancy is 50% maximum?_

The `FillPercent` only affects how pages are split when they are filled. `WriteTo()` has the same affect as any other read-only transaction and simply prevents pages in that transaction from being reused. If you are copying for a long time then your database will start to grow.

It's best not to run `Tx.WriteTo()` over a slow connection if your DB is large. It's better to copy the file locally to your hard drive, stop the transaction, and then transfer the copied file over the slow connection.
